# Generated by Django 6.0 on 2025-12-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('septic', 'Septic Tank'), ('pit_latrine', 'Pit Latrine'), ('grease_trap', 'Grease Trap'), ('other', 'Other')], default='septic', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tank_size',
            field=models.CharField(choices=[('1000', '1000 Liters'), ('2000', '2000 Liters'), ('3000', '3000 Liters'), ('5000', '5000 Liters'), ('10000', '10000 Liters')], default='1000', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
