# Generated by Django 6.0 on 2026-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_rating_admin_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.FloatField(blank=True, default=0.0, help_text='Distance traveled in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fuel_used_liters',
            field=models.FloatField(blank=True, default=0.0, help_text='Fuel used for this job', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='waste_emptied_liters',
            field=models.FloatField(blank=True, default=0.0, help_text='Amount of waste emptied in liters', null=True),
        ),
    ]
