# Generated by Django 6.0 on 2026-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_driverslot_booking_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
