# Generated by Django 6.0 on 2026-01-12 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_status'),
        ('payments', '0003_transactionlog_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bank_reference'], name='payments_pa_bank_re_539435_idx'),
        ),
    ]
