# Generated by Django 6.0 on 2026-04-22 06:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_rating_admin_review'),
        ('payments', '0004_payment_bank_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_mpesa_r_10ee83_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_checkou_e4cf10_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='mpesa_receipt',
            new_name='invoice_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='intasend_api_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_provider',
            field=models.CharField(choices=[('intasend', 'IntaSend'), ('mpesa', 'M-PESA')], default='intasend', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money (M-Pesa)'), ('card', 'Card Payment'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash')], default='mobile_money', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['intasend_api_ref'], name='payments_pa_intasen_112267_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice_id'], name='payments_pa_invoice_fcb1dc_idx'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='checkout_request_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='merchant_request_id',
        ),
    ]
