# Generated by Django 6.0 on 2026-04-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_two_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='driver_license_expiry_date',
            field=models.DateField(blank=True, help_text='Driver license expiry date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
