# Generated by Django 6.0 on 2026-04-27

from django.db import migrations


def convert_empty_to_null(apps, schema_editor):
    """Convert empty phone numbers to NULL to avoid UNIQUE constraint issues"""
    User = apps.get_model('users', 'User')
    User.objects.filter(phone_number='').update(phone_number=None)


def revert_null_to_empty(apps, schema_editor):
    """Reverse: convert NULL back to empty (shouldn't be needed)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_number'),
    ]

    operations = [
        migrations.RunPython(convert_empty_to_null, revert_null_to_empty),
    ]
