# Generated by Django 6.0 on 2026-04-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_convert_empty_phone_to_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_driver_approved',
            field=models.BooleanField(default=False, help_text='Whether driver account is approved by admin'),
        ),
    ]
